### ISSUE TITLE
Regression of #28: UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by gijswijs** [mmagnus/Pocket-Plus-Calibre-Plugin#59]
The issue #28 seems to have returned. 

Plugin version: 2.7.4
Calibre: 7.18
Ubuntu 24.04.1 

Let me know if I can help to fix this.

**Comment by gijswijs** [comment]
After digging around a bit, it's more a regression of #56 . If I hardcode the amount of articles to say 100, everything seems to work.

**Comment by mmagnus** [comment]
Thanks for the info, probably we should comment on that somewhere.

**Comment by Hunter321noooob** [comment]
> After digging around a bit, it's more a regression of #56 . If I hardcode the amount of articles to say 100, everything seems to work.

Sorry, I don't understand how you solved it, I saved 63 pockets, tried to download and it gave me an error, I added another 90, and still an error, I limited MAX_ARTICLES_PER_FEED =  
500 to 100 to 50 to 10. But it still doesn't work. I've been trying to download for days. Thanks in advance

**Comment by gijswijs** [comment]
I hardcoded the amount of articles in the recipe by putting a low number here:
https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/blob/master/Pocket.recipe#L285
Replaced that whole line with `50,` (or maybe even less, I forgot the specific number)

**Comment by j2ankit** [comment]
Despite hard-coding I continue to face the same issue. 
I went with a count of 20 as the max count as mentioned in Pocket API documentation is 30. 

Any help and guidance is appreciated. Thanks!

The error I get is "UnboundLocalError: cannot access local variable 'response' where it is not associated with a value" 

System details
OS: Debian 12
Calibre: 7.20
Plugin: 2.7.4

**Comment by gijswijs** [comment]
I think there's another issue when you have no tagged articles at all. My
eye fell on it when checking the code, but I'm not 100% sure. Will report
back asap and open a separate issue (and with luck a PR) if needed.

**Comment by alvaroreig** [comment]
Hi there @j2ankit 

I can confirm the issue. Using latest version produces the same error.

I don't have time to properly debug this, but the error is due to using a value too high in 285, where we do:

`self.max_articles * 1000,  # something "unlimited"`

Where self.max_articles is set in line 172:

`max_articles = MAX_ARTICLES`

Which in turn comes from line 64:

`MAX_ARTICLES = 1000`

So, max articles in pocket API request is 1.000.000, which must be too high.

If you set up MAX_ARTICLES to 4, which makes 4.000 in the pocket API, it works ok.

So I have submited a patch that removes the  "*1000" multiplier, so the default value of 1000 works.

We should investigate more and log Pocket's API errors
